spring:
  config:
    import: optional:configserver:http://configuser:${CONFIG_SERVER_PASSWORD:configpassword}@${CONFIG_SERVER_HOST:config-server:8888}
  application:
    name: notifications-ms
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH:true}
          starttls:
            enable: ${MAIL_STARTTLS:true}
grpc:
  server:
    port: 9090
    enabled: true

server:
  port: 8082
