spring:
  mail:
    host: smtp.gmail.com
    port: 587  # Puerto correcto para TLS
    username: ${SMTP_USERNAME} #Correo del remitente maestro (Persona/Empresa que envia los correos) Remitente
    password: ${SMTP_PASSWORD} # La contraseña debe ser ingresada (genera una por contraseña de aplicaciones en google)
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  # Habilita STARTTLS
          connectiontimeout: 5000
          timeout: 5000