spring:
  config:
    import: optional:configserver:http://configuser:${CONFIG_SERVER_PASSWORD:configpassword}@${CONFIG_SERVER_HOST:config-server:8888}
  application:
    name: notifications-ms
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}


#Puertos para el servidor web y gRPC
server:
  port: 8080

grpc:
  server:
    port: 9090
