spring:
  config:
    import: optional:configserver:http://configuser:${CONFIG_SERVER_PASSWORD:configpassword}@${CONFIG_SERVER_HOST:config-server:8888}
  application:
    name: notifications-ms
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:tarrillollontopvictormanuel04@gmail.com}
    password: ${MAIL_PASSWORD:kppuphzpviyknkeo}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH:true}
          starttls:
            enable: ${MAIL_STARTTLS:true}