spring:
  mail:
    host: smtp.gmail.com
    port: 587  # Puerto correcto para TLS
    username: example@correo.com #Elcorreo
    password: "Contraseña de Aplicacion" # La contraseña debe ser ingresada en texto plano
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  # Habilita STARTTLS
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000